output:
#  writer: indis.output.json_writer.JsonFileWriter
#  configuration:
#    directory: /tmp/director

  writer: indis.output.api_writer.APIWriter
  configuration:
    url: http://localhost:8888/icingaweb2/director
    user: icingaadmin
    password: icinga
    # Automatically do a deploy after all create, changes and deletes is done, default false
    deploy: true
    # If delete is used it's a MUST that a full population from a source is collected from the source
    # Require that cache is enabled, default false
    delete: true


source:
  demo_source:
    name: demo
    class: demo.source.NetworkSource
    # This part describe how the data I read by the cmdb module
    access:
      # This is mandatory is the class that define the abstract methods that the reader implementation
      # must implement. The module class should only know about this class.
      reader_inf: demo.reader.Reader
      # This defines the real implementation. This is not mandatory, but than be supplied in runtime.
      reader: demo.file_reader.FileReader

  demo_template:
    name: demo_host_template
    class: demo_host_template.source.NetworkSource
    # This part describe hsource_dataow the data I read by the cmdb module
    access:
      # This is mandatory is the class that define the abstract methods that the reader implementation
      # must implement. The module class should only know about this class.
      reader_inf: demo_host_template.reader.Reader
      # This defines the real implementation. This is not mandatory, but than be supplied in runtime.
      reader: demo_host_template.file_reader.FileReader

processor:
  # Add vars to all and specific object types
  vars:
    common:
      env: Sthlm
    hosts:
      template: base_host
    services:
      dc: dc1

  groups:
    hosts:
      - all_host_group

cache:
  # Use cache to enable life cycle on objects. A must to understand deletes
  # data will be stored in redis with the prefix of the source name, e.g. "demo_source:", as a way to separate between
  # different sources
  redis:
    host: localhost


demo:

  # Provider specific attribute used in the provider logic
  nodefile: data/source_data.json

demo_host_template:

  # Provider specific attribute used in the provider logic
  nodefile: data/host_template.json

logger:
  # Path and name for the log file. Default is stdout
  #logfile: /var/tmp/mender.log
  # Log level. Default INFO
  level: DEBUG
